import {
  Circle,
  Clock,
  Loader2,
  PauseCircle,
  Hourglass,
  CheckCircle2,
  XCircle,
  Ban,
  AlertOctagon,
  AlertTriangle,
  HeartPulse,
  HelpCircle,
} from "lucide-react";
import type { SemanticStatus, StatusDefinition } from "@/types/status";

export const STATUS_REGISTRY: Record<SemanticStatus, StatusDefinition> = {
  idle: {
    status: "idle",
    label: "Idle",
    description: "Component or worker is initialized and awaiting tasks.",
    category: "neutral",
    icon: Circle,
    badgeClasses: "bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700",
    dotClasses: "bg-slate-400 dark:bg-slate-500",
    iconClasses: "text-slate-500 dark:text-slate-400",
    ariaLabel: "Status: Idle",
  },
  queued: {
    status: "queued",
    label: "Queued",
    description: "Task or request is enqueued waiting for execution capacity.",
    category: "info",
    icon: Clock,
    badgeClasses: "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950/60 dark:text-blue-300 dark:border-blue-800",
    dotClasses: "bg-blue-500 dark:bg-blue-400",
    iconClasses: "text-blue-500 dark:text-blue-400",
    ariaLabel: "Status: Queued",
  },
  running: {
    status: "running",
    label: "Running",
    description: "Execution is currently active and processing in real-time.",
    category: "info",
    icon: Loader2,
    badgeClasses: "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/60 dark:text-sky-300 dark:border-sky-800",
    dotClasses: "bg-sky-500 dark:bg-sky-400 animate-pulse",
    iconClasses: "text-sky-600 dark:text-sky-400 animate-spin",
    ariaLabel: "Status: Running",
  },
  paused: {
    status: "paused",
    label: "Paused",
    description: "Execution is temporarily suspended and can be resumed.",
    category: "warning",
    icon: PauseCircle,
    badgeClasses: "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/60 dark:text-amber-300 dark:border-amber-800",
    dotClasses: "bg-amber-500 dark:bg-amber-400",
    iconClasses: "text-amber-600 dark:text-amber-400",
    ariaLabel: "Status: Paused",
  },
  waiting_approval: {
    status: "waiting_approval",
    label: "Waiting Approval",
    description: "Requires explicit operator or supervisor authorization to proceed.",
    category: "warning",
    icon: Hourglass,
    badgeClasses: "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/60 dark:text-purple-300 dark:border-purple-800",
    dotClasses: "bg-purple-500 dark:bg-purple-400",
    iconClasses: "text-purple-600 dark:text-purple-400",
    ariaLabel: "Status: Waiting Approval",
  },
  completed: {
    status: "completed",
    label: "Completed",
    description: "Process finished successfully with all goals satisfied.",
    category: "success",
    icon: CheckCircle2,
    badgeClasses: "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/60 dark:text-emerald-300 dark:border-emerald-800",
    dotClasses: "bg-emerald-500 dark:bg-emerald-400",
    iconClasses: "text-emerald-600 dark:text-emerald-400",
    ariaLabel: "Status: Completed",
  },
  failed: {
    status: "failed",
    label: "Failed",
    description: "Process terminated abnormally or encountered fatal errors.",
    category: "destructive",
    icon: XCircle,
    badgeClasses: "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/60 dark:text-rose-300 dark:border-rose-800",
    dotClasses: "bg-rose-500 dark:bg-rose-400",
    iconClasses: "text-rose-600 dark:text-rose-400",
    ariaLabel: "Status: Failed",
  },
  cancelled: {
    status: "cancelled",
    label: "Cancelled",
    description: "Execution was aborted by operator command or system timeout.",
    category: "neutral",
    icon: Ban,
    badgeClasses: "bg-stone-100 text-stone-700 border-stone-200 dark:bg-stone-800 dark:text-stone-300 dark:border-stone-700",
    dotClasses: "bg-stone-400 dark:bg-stone-500",
    iconClasses: "text-stone-500 dark:text-stone-400",
    ariaLabel: "Status: Cancelled",
  },
  blocked: {
    status: "blocked",
    label: "Blocked",
    description: "Execution is prevented by policy violation, missing dependency, or quota.",
    category: "destructive",
    icon: AlertOctagon,
    badgeClasses: "bg-red-50 text-red-700 border-red-200 dark:bg-red-950/60 dark:text-red-300 dark:border-red-800",
    dotClasses: "bg-red-500 dark:bg-red-400",
    iconClasses: "text-red-600 dark:text-red-400",
    ariaLabel: "Status: Blocked",
  },
  degraded: {
    status: "degraded",
    label: "Degraded",
    description: "Service is operational but experiencing elevated latency or partial outages.",
    category: "warning",
    icon: AlertTriangle,
    badgeClasses: "bg-orange-50 text-orange-700 border-orange-200 dark:bg-orange-950/60 dark:text-orange-300 dark:border-orange-800",
    dotClasses: "bg-orange-500 dark:bg-orange-400",
    iconClasses: "text-orange-600 dark:text-orange-400",
    ariaLabel: "Status: Degraded",
  },
  healthy: {
    status: "healthy",
    label: "Healthy",
    description: "Service or subsystem is operating nominally with full SLA compliance.",
    category: "success",
    icon: HeartPulse,
    badgeClasses: "bg-teal-50 text-teal-700 border-teal-200 dark:bg-teal-950/60 dark:text-teal-300 dark:border-teal-800",
    dotClasses: "bg-teal-500 dark:bg-teal-400",
    iconClasses: "text-teal-600 dark:text-teal-400",
    ariaLabel: "Status: Healthy",
  },
  unknown: {
    status: "unknown",
    label: "Unknown",
    description: "Status could not be determined or is not reported.",
    category: "neutral",
    icon: HelpCircle,
    badgeClasses: "bg-zinc-100 text-zinc-700 border-zinc-200 dark:bg-zinc-800 dark:text-zinc-300 dark:border-zinc-700",
    dotClasses: "bg-zinc-400 dark:bg-zinc-500",
    iconClasses: "text-zinc-500 dark:text-zinc-400",
    ariaLabel: "Status: Unknown",
  },
};

export function getStatusDefinition(status: SemanticStatus | string): StatusDefinition {
  if (status in STATUS_REGISTRY) {
    return STATUS_REGISTRY[status as SemanticStatus];
  }
  return STATUS_REGISTRY.unknown;
}
