"""Layer 7: Code Context Compression Engine for JakeAI Platform.

Implements Section 2 Layer 7 of 03_TOKEN_OPTIMIZATION.md:
1. Diff pruning: prunes unchanged lines in unified git diffs while preserving modified hunks.
2. Generated-file exclusion: summarizes or excludes package-lock.json, go.sum, *.min.js, autogenerated headers.
3. Repository noise reduction: removes comment noise & layout bloat from non-critical files.
4. AST skeletonization integration: coordinates with CodeSkeletonizer.
5. Symbol/reference preservation: keeps critical target symbols intact.
6. Guardrail: Strictly NO-OP for normal chat workloads.
"""

from __future__ import annotations

import logging
import re
from typing import Any

from pydantic import BaseModel, Field

from app.optimizer.ast_skeletonizer import CodeSkeletonizer, get_code_skeletonizer
from app.optimizer.contracts import OptimizationLevel
from app.optimizer.token_pruner import estimate_tokens

logger = logging.getLogger(__name__)

GENERATED_FILE_PATTERNS = [
    re.compile(r"\bpackage-lock\.json\b", re.IGNORECASE),
    re.compile(r"\bgo\.sum\b", re.IGNORECASE),
    re.compile(r"\bpnpm-lock\.yaml\b", re.IGNORECASE),
    re.compile(r"\byarn\.lock\b", re.IGNORECASE),
    re.compile(r"\bCargo\.lock\b", re.IGNORECASE),
    re.compile(r"\.min\.(?:js|css)\b", re.IGNORECASE),
    re.compile(r"\.map\b", re.IGNORECASE),
]

AUTOGENERATED_HEADER_REGEX = re.compile(
    r"(?:/\*[\s\S]*?(?:auto-?generated|code generated by|do not edit)[\s\S]*?\*/"
    r"|//\s*code generated by .* do not edit\."
    r"|#\s*auto-?generated by .* do not edit)",
    re.IGNORECASE,
)


class CodeCompressionResult(BaseModel):
    """Outcome of code context compression."""

    compressed_code: str
    raw_tokens: int
    compressed_tokens: int
    tokens_saved: int
    compression_ratio: float = Field(
        ...,
        description="Percentage of tokens pruned: (tokens_saved / raw_tokens) * 100",
    )
    diff_lines_pruned: int = 0
    generated_files_omitted: int = 0
    transformations: list[str] = Field(default_factory=list)
    fallback_used: bool = False
    fallback_reason: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class CodeContextCompressor:
    """Specialized compressor for coding, repository, and diff contexts."""

    def __init__(
        self,
        skeletonizer: CodeSkeletonizer | None = None,
    ) -> None:
        self.skeletonizer = skeletonizer or get_code_skeletonizer()

    @staticmethod
    def prune_git_diff(diff_text: str, max_context_lines: int = 3) -> tuple[str, int]:
        """Prune unchanged context padding lines from unified diffs.

        Preserves all diff headers (diff --git, index, ---, +++, @@), all addition lines (+),
        and all deletion lines (-), while collapsing long runs of unchanged lines ( ).
        """
        lines = diff_text.splitlines()
        pruned_lines: list[str] = []
        unchanged_buffer: list[str] = []
        pruned_count = 0

        def flush_unchanged() -> None:
            nonlocal unchanged_buffer, pruned_count
            if not unchanged_buffer:
                return
            if len(unchanged_buffer) <= (max_context_lines * 2):
                pruned_lines.extend(unchanged_buffer)
            else:
                head = unchanged_buffer[:max_context_lines]
                tail = unchanged_buffer[-max_context_lines:]
                omitted = len(unchanged_buffer) - (max_context_lines * 2)
                pruned_lines.extend(head)
                pruned_lines.append(f" ... [{omitted} unchanged lines omitted] ...")
                pruned_lines.extend(tail)
                pruned_count += omitted
            unchanged_buffer = []

        for line in lines:
            if (
                line.startswith("@@")
                or line.startswith("diff ")
                or line.startswith("---")
                or line.startswith("+++")
                or line.startswith("+")
                or line.startswith("-")
            ):
                flush_unchanged()
                pruned_lines.append(line)
            elif line.startswith(" ") or (not line and unchanged_buffer):
                unchanged_buffer.append(line)
            else:
                flush_unchanged()
                pruned_lines.append(line)

        flush_unchanged()
        return "\n".join(pruned_lines), pruned_count

    @staticmethod
    def exclude_generated_noise(content: str, filename: str = "") -> tuple[str, bool]:
        """Detect and summarize generated lockfiles, minified bundles, or code generator noise."""
        is_lockfile = any(
            pat.search(filename) for pat in GENERATED_FILE_PATTERNS
        ) or any(pat.search(content[:300]) for pat in GENERATED_FILE_PATTERNS)
        if is_lockfile:
            line_count = len(content.splitlines())
            summary = (
                f"[Generated Lockfile/Asset: {filename or 'dependency-lock'} "
                f"({line_count} lines omitted for context efficiency)]"
            )
            return summary, True

        # Check for autogenerated disclaimers in headers
        if AUTOGENERATED_HEADER_REGEX.search(content[:500]):
            cleaned = AUTOGENERATED_HEADER_REGEX.sub(
                "// [Autogenerated header omitted]", content, count=1
            )
            return cleaned, True

        return content, False

    def compress_code_context(
        self,
        context_text: str,
        is_coding_workload: bool = True,
        level: OptimizationLevel = OptimizationLevel.BALANCED,
        preserve_symbols: set[str] | None = None,
        filename: str = "",
    ) -> CodeCompressionResult:
        """Compress code context while strictly preserving semantic correctness and required symbols.

        Guardrail: If not a coding workload, returns context unchanged without token pruning.
        """
        raw_tokens = estimate_tokens(context_text)
        if not is_coding_workload or not context_text.strip():
            # Guardrail: Do not apply code compression to normal chat
            return CodeCompressionResult(
                compressed_code=context_text,
                raw_tokens=raw_tokens,
                compressed_tokens=raw_tokens,
                tokens_saved=0,
                compression_ratio=0.0,
                transformations=[],
            )

        current_text = context_text
        transformations: list[str] = []
        diff_pruned = 0
        gen_omitted = 0

        # 1. Step A: Check for Generated Lockfiles / Assets
        cleaned_gen, is_gen = self.exclude_generated_noise(
            current_text, filename=filename
        )
        if is_gen:
            current_text = cleaned_gen
            transformations.append("generated_file_noise_exclusion")
            gen_omitted += 1

        # 2. Step B: Diff Pruning if diff syntax is detected
        if "diff --git" in current_text or (
            current_text.startswith("--- ") and "\n+++ " in current_text
        ):
            pruned_diff, count = self.prune_git_diff(current_text)
            if count > 0:
                current_text = pruned_diff
                diff_pruned = count
                transformations.append(f"git_diff_pruning_{count}_lines")

        fallback_used = False
        fallback_reason: str | None = None

        # 3. Step C: AST Code Skeletonization (for code blocks or raw python)
        if level != OptimizationLevel.CONSERVATIVE:
            if "```" in current_text:
                skeletonized = self.skeletonizer.skeletonize_markdown_blocks(
                    current_text,
                    level=level,
                    preserve_symbols=preserve_symbols,
                )
                if skeletonized != current_text:
                    current_text = skeletonized
                    transformations.append(f"ast_skeletonize_{level.value}")
            elif "def " in current_text or "class " in current_text:
                ast_res = self.skeletonizer.skeletonize_python(
                    current_text,
                    level=level,
                    preserve_symbols=preserve_symbols,
                )
                if ast_res.success and ast_res.skeleton_code != current_text:
                    current_text = ast_res.skeleton_code
                    transformations.append(f"ast_skeletonize_raw_{level.value}")
                elif not ast_res.success:
                    fallback_used = True
                    fallback_reason = ast_res.error
                    transformations.append("fail_closed_fallback_raw")

        compressed_tokens = estimate_tokens(current_text)
        tokens_saved = max(0, raw_tokens - compressed_tokens)
        compression_ratio = (
            round((tokens_saved / raw_tokens) * 100, 2) if raw_tokens > 0 else 0.0
        )

        return CodeCompressionResult(
            compressed_code=current_text,
            raw_tokens=raw_tokens,
            compressed_tokens=compressed_tokens,
            tokens_saved=tokens_saved,
            compression_ratio=compression_ratio,
            diff_lines_pruned=diff_pruned,
            generated_files_omitted=gen_omitted,
            transformations=transformations,
            fallback_used=fallback_used,
            fallback_reason=fallback_reason,
        )


_code_context_compressor: CodeContextCompressor | None = None


def get_code_context_compressor() -> CodeContextCompressor:
    """Singleton getter for CodeContextCompressor."""
    global _code_context_compressor
    if _code_context_compressor is None:
        _code_context_compressor = CodeContextCompressor()
    return _code_context_compressor
